import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["selector", '[data-theme="dark"]'],
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        erp: {
          // Brand Colors (Atelier Architectural Navy)
          navy: {
            DEFAULT: "var(--erp-navy)",
            hover: "var(--erp-navy-hover)",
            light: "var(--erp-navy-light)",
            50: "var(--erp-navy-50)",
            100: "var(--erp-navy-100)",
            200: "var(--erp-navy-200)",
            300: "var(--erp-navy-300)",
            400: "var(--erp-navy-400)",
            500: "var(--erp-navy-500)",
            600: "var(--erp-navy-600)",
            700: "var(--erp-navy-700)",
            800: "var(--erp-navy-800)",
            900: "var(--erp-navy-900)",
            950: "var(--erp-navy-950)",
          },
          // Architectural Ice Slate Scale (50-900)
          slate: {
            50: "var(--erp-slate-50)",
            100: "var(--erp-slate-100)",
            200: "var(--erp-slate-200)",
            300: "var(--erp-slate-300)",
            400: "var(--erp-slate-400)",
            500: "var(--erp-slate-500)",
            600: "var(--erp-slate-600)",
            700: "var(--erp-slate-700)",
            800: "var(--erp-slate-800)",
            900: "var(--erp-slate-900)",
          },
          "navy-hover": "var(--erp-navy-hover)",
          "navy-light": "var(--erp-navy-light)",
          canvas: "var(--erp-canvas)",
          surface: "var(--erp-surface)",
          "surface-muted": "var(--erp-surface-muted)",
          "surface-subtle": "var(--erp-surface-subtle)",
          border: "var(--erp-border)",
          "border-subtle": "var(--erp-border-subtle)",
          "border-strong": "var(--erp-border-strong)",
          "text-main": "var(--erp-text-main)",
          "text-body": "var(--erp-text-body)",
          "text-muted": "var(--erp-text-muted)",
          "text-subtle": "var(--erp-text-subtle)",
          warning: "var(--erp-warning)",
          "warning-bg": "var(--erp-warning-bg)",
          "warning-border": "var(--erp-warning-border)",
          "warning-text": "var(--erp-warning-text)",
          danger: "var(--erp-danger)",
          "danger-bg": "var(--erp-danger-bg)",
          "danger-border": "var(--erp-danger-border)",
          success: "var(--erp-success)",
          "success-bg": "var(--erp-success-bg)",
          "success-border": "var(--erp-success-border)",
          info: "var(--erp-info)",
          "info-bg": "var(--erp-info-bg)",
        },
      },
      borderRadius: {
        DEFAULT: "0px",
        none: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        "3xl": "0px",
        full: "0px",
      },
    },
  },
  plugins: [],
};

export default config;
