<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\TanErp.Application\TanErp.Application.csproj" />
    <ProjectReference Include="..\TanErp.Domain\TanErp.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="FirebaseAdmin" />
  </ItemGroup>
</Project>
